services:
  postgres:
    container_name: postgres_produtosapi
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=produtosapi'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5432'
  pgadmin:
    container_name: pgadmin4_produtosapi
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"